gText_Birch_Welcome::
    .string "By the stars!\n"
	.string "\p"
    .string "...\n"
	.string "......................\p"
    .string "Fate has woven us together\n"
    .string "in a peculiar way.\p"
    .string "You’ve stumbled into my world\n"
    .string "through an unexpected connection\n"
    .string "of the planes!\p"
    .string "This twist of destiny is unexpected\n"
    .string "and quite astonishing.\p"
    .string "It seems fate has led you here,\n"
    .string "and I must embrace it as a sign.\p"
    .string "$"

gText_Birch_Pokemon::
    .string "Our world is caught in a delicate\n"
    .string "balance between light and darkness.\n"
    .string "You are here because a great\n"
    .string "upheaval is imminent.\p"
    .string "Your first trial is the Enchanted\n"
    .string "Forest, a maze filled with ancient\n"
    .string "secrets and dangers.\n"
    .string "Beyond the forest lies Khemia,\n"
    .string "where your true journey will begin.\p"
    .string "$"

gText_Birch_MainSpeech::
    .string "Ah, reminds me of my time in Astral Plane.\n"
    .string "Such journeys revealed fragility of our world.\n"
    .string "The path ahead holds many challenges.\n"
    .string "But remember, destiny has chosen you for this quest.\n"
    .string "$"

gText_Birch_AndYouAre::
    .string "Hmm, do you remember who you are?\n"
    .string "It seems your memories are a bit unclear.\n"
    .string "Let me assist you in recalling them.\n"
	.string "\n"
    .string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
    .string "Your past is now insignificant, and\n"
    .string "you stand on the brink of a new destiny.\p"
    .string "To start anew, you need a name\n"
    .string "that will resonate with the weight of the cosmos.\n"
    .string "What name shall you claim for this\n"
    .string "new chapter in the grand tapestry?$"
	
gText_Birch_SoItsPlayer::
	.string "Ah, so it is {PLAYER}{KUN}?\n"
	.string "A name that resonates with the echoes of fate itself.\n"
	.string "You are destined to walk this path and face the trials ahead.\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Are you ready to step into your new life?\n"
	.string "Venture through the cave\n"
	.string "and face the journey ahead...\p"
	.string "Oh, wait! Someone's shaking me!\n"
	.string "The connection...\n"
	.string "It's breaking apart!\p"
	.string "Stay resolute, {PLAYER}.\n"
    .string "Fate has led you here…$"

gText_Birch_AreYouReady::
	.string "Oh, this is quite the predicament!\n"
	.string "Must… finish… message…\n"
	.string "The connection… it’s breaking…!\n"
    .string "I can barely… hold on…\p"
	.string "The fate is yours…\n"
	.string "don’t forget what I’ve told you…!\p"
	.string "Fading… must… end…\n"
	.string "…\n"
	.string "$"
