gText_Birch_Welcome::
    .string "By the stars! Fate has woven\n"
    .string "us together in a peculiar way.\n"
    .string "You’ve stumbled into my world\n"
    .string "through an unexpected connection\n"
    .string "of the planes!\p"
    .string "As a prophet, this twist of destiny\n"
    .string "is surprising.\n"
    .string "It seems fate has led you here,\n"
    .string "and I must accept it as a sign.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Our world is caught in a delicate balance between light and darkness.\n"
	.string "You are here because a great upheaval is imminent.\p"
	.string "Your first trial is the Enchanted Forest, a maze filled with ancient secrets and dangers.\n"
	.string "Beyond the forest lies Khemia, where your true journey will begin.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ah, yes, this reminds me of a time I once wandered the Astral Plane.\n"
	.string "Such experiences taught me the fragility of balance in our world.\p"
	.string "Prepare yourself, for the path ahead is fraught with challenges and revelations.\n"
	.string "But remember, destiny has chosen you for this quest.\p"
	.string "$"

gText_Birch_AndYouAre::
    .string "Now, tell me, who might you be in this new chapter of existence?\n"
    .string "Your memory feels blurry?\n"
    .string "Let me help you recall?$"


gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Can you recall your name from before?\n"
	.string "What shall I call you in our world?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\n"
	.string "A name that carries the weight of destiny, I see.\n"
	.string "You are the one who will embark on this quest and confront the challenges ahead.\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Are you ready to begin?\n"
	.string "Step through the cave and embrace the adventure that awaits…\p"
	.string "Oh, it seems… ah! Someone's shaking me! The connection… it’s unstable!\p"
	.string "Stay focused on your path, {PLAYER}. Remember, fate has led you here…$"

gText_Birch_AreYouReady::
	.string "Oh, this is quite the predicament! Must… finish… message…\n"
	.string "The connection… it’s breaking…! I can barely… hold on…\p"
	.string "The fate is yours… don’t forget what I’ve told you…!\n"
	.string "Fading… must… end…\p"
	.string "…\n"
	.string "$"
