# 1 "data/maps/Descend/scripts.pory"

# 2 "data/maps/Descend/scripts.pory"
Descend_MapScripts::
# 3 "data/maps/Descend/scripts.pory"
	.byte 0
# 4 "data/maps/Descend/scripts.pory"

# 5 "data/maps/Descend/scripts.pory"
Descend_EventScript_SelfPathSign::
# 6 "data/maps/Descend/scripts.pory"
	msgbox Descend_Text_SelfPathSign, MSGBOX_SIGN
# 7 "data/maps/Descend/scripts.pory"
	end
# 8 "data/maps/Descend/scripts.pory"

# 9 "data/maps/Descend/scripts.pory"
	Descend_Text_SelfPathSign:
# 10 "data/maps/Descend/scripts.pory"
	.string "On the path of the Self.$"
# 11 "data/maps/Descend/scripts.pory"

# 12 "data/maps/Descend/scripts.pory"
Descend_EventScript_AllPathSign::
# 13 "data/maps/Descend/scripts.pory"
	msgbox Descend_Text_AllPathSign, MSGBOX_SIGN
# 14 "data/maps/Descend/scripts.pory"
	end
# 15 "data/maps/Descend/scripts.pory"

# 16 "data/maps/Descend/scripts.pory"
	Descend_Text_AllPathSign:
# 17 "data/maps/Descend/scripts.pory"
	.string "On the path of the All.$"
