# 1 "data/maps/EnchantedForest/scripts.pory"

# 2 "data/maps/EnchantedForest/scripts.pory"
  
# 3 "data/maps/EnchantedForest/scripts.pory"
  
# 4 "data/maps/EnchantedForest/scripts.pory"
   EnchantedForest_MapScripts::
# 5 "data/maps/EnchantedForest/scripts.pory"
	.byte 0
# 6 "data/maps/EnchantedForest/scripts.pory"

# 7 "data/maps/EnchantedForest/scripts.pory"

# 8 "data/maps/EnchantedForest/scripts.pory"

# 9 "data/maps/EnchantedForest/scripts.pory"
Enchanted_EventScript_SahiraEOC::
# 10 "data/maps/EnchantedForest/scripts.pory"
	msgbox EnchantedForest_Text_SahiraEndOfContent, MSGBOX_NPC
# 11 "data/maps/EnchantedForest/scripts.pory"
	end
# 12 "data/maps/EnchantedForest/scripts.pory"

# 13 "data/maps/EnchantedForest/scripts.pory"

# 14 "data/maps/EnchantedForest/scripts.pory"

# 15 "data/maps/EnchantedForest/scripts.pory"

# 16 "data/maps/EnchantedForest/scripts.pory"

# 17 "data/maps/EnchantedForest/scripts.pory"

# 18 "data/maps/EnchantedForest/scripts.pory"
EnchantedForest_Text_SahiraEndOfContent:
# 19 "data/maps/EnchantedForest/scripts.pory"
    .string "SAHIRA: Well done, {PLAYER}{KUN}!\n"
# 20 "data/maps/EnchantedForest/scripts.pory"
    .string "You made it out of the Enchanted Forest!\p"
# 21 "data/maps/EnchantedForest/scripts.pory"
    .string "Thank you for supporting our\n"
# 22 "data/maps/EnchantedForest/scripts.pory"
    .string "early version of the game.\p"
# 23 "data/maps/EnchantedForest/scripts.pory"
    .string "We appreciate your patience\n"
# 24 "data/maps/EnchantedForest/scripts.pory"
    .string "with any flaws you may have found\p"
# 25 "data/maps/EnchantedForest/scripts.pory"
    .string "or will encounter.\n"
# 26 "data/maps/EnchantedForest/scripts.pory"
    .string "=p\p"
# 27 "data/maps/EnchantedForest/scripts.pory"
    .string "This is where the current content ends.\n"
# 28 "data/maps/EnchantedForest/scripts.pory"
    .string "\p"
# 29 "data/maps/EnchantedForest/scripts.pory"
    .string "Please provide feedback on the game\n"
# 30 "data/maps/EnchantedForest/scripts.pory"
    .string "and what you hope to see in the future.\p"
# 31 "data/maps/EnchantedForest/scripts.pory"
    .string "Shino gives his regards, he wish you try\n"
# 32 "data/maps/EnchantedForest/scripts.pory"
    .string "the next version on distant future!$"
